/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports` | `/compliance-reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/all-sites` | `/compliance-reports/all-sites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/pending-submission` | `/compliance-reports/pending-submission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/submit-report` | `/compliance-reports/submit-report`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/compliance-reports` | `/compliance-reports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/compliance-reports/all-sites` | `/compliance-reports/all-sites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/compliance-reports/pending-submission` | `/compliance-reports/pending-submission`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/compliance-reports/submit-report` | `/compliance-reports/submit-report`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/compliance-reports${`?${string}` | `#${string}` | ''}` | `/compliance-reports${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/compliance-reports/all-sites${`?${string}` | `#${string}` | ''}` | `/compliance-reports/all-sites${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/compliance-reports/pending-submission${`?${string}` | `#${string}` | ''}` | `/compliance-reports/pending-submission${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/compliance-reports/submit-report${`?${string}` | `#${string}` | ''}` | `/compliance-reports/submit-report${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports` | `/compliance-reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/all-sites` | `/compliance-reports/all-sites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/pending-submission` | `/compliance-reports/pending-submission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/compliance-reports/submit-report` | `/compliance-reports/submit-report`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
